######################################################################
#
# File name : tb_compile.do
# Created on: Wed Oct 18 11:56:44 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -mfcu -work xil_defaultlib  "+incdir+../../../../neorv32.srcs/sources_1/new" \
"../../../../neorv32.srcs/sources_1/new/ip_fifo.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_alu.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_control.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_cp_div_ser.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_cp_mul_dsp.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_cp_mul_ser.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_cp_shifter_ser.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_decompressor.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_lsu.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_pmp.v" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_regfile.v" \
"../../../../neorv32.srcs/sources_1/new/system_test.v" \
"../../../../neorv32.srcs/sources_1/new/wb_dpram.v" \
"../../../../neorv32.srcs/sources_1/new/wb_ram.v" \

vlog -64 -incr -mfcu -sv -work xil_defaultlib  "+incdir+../../../../neorv32.srcs/sources_1/new" \
"../../../../neorv32.srcs/sources_1/new/rv32_cpu_cp_shifter_barrel.v" \
"../../../../neorv32.srcs/sim_1/new/tb.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

