######################################################################
#
# File name : tb_fifo_wave.do
# Created on: Wed Oct 11 14:24:28 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
