######################################################################
#
# File name : tb_fifo_elaborate.do
# Created on: Wed Oct 11 14:24:27 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_fifo xil_defaultlib.glbl -o tb_fifo_opt
