######################################################################
#
# File name : tb_fifo_compile.do
# Created on: Wed Oct 11 14:24:27 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -mfcu -work xil_defaultlib  "+incdir+../../../../neorv32.srcs/sources_1/new" \
"../../../../neorv32.srcs/sources_1/new/ip_fifo.v" \

vlog -64 -incr -mfcu -sv -work xil_defaultlib  "+incdir+../../../../neorv32.srcs/sources_1/new" \
"../../../../neorv32.srcs/sim_1/new/tb_fifo.sv" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

