######################################################################
#
# File name : tb_simulate.do
# Created on: Wed Oct 18 11:56:45 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_wave.do}

view wave
view structure
view signals

log -r /*

do {tb.udo}

run -all
