######################################################################
#
# File name : tb_wave.do
# Created on: Wed Oct 18 11:56:45 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
