######################################################################
#
# File name : tb_compile.do
# Created on: Thu Nov 09 13:46:36 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -mfcu -work xil_defaultlib  \
"../../../../lsu.srcs/sources_1/new/rv32_dcache.v" \
"../../../../lsu.srcs/sources_1/new/rv32_dmem.v" \
"../../../../lsu.srcs/sources_1/new/rv32_lsu2.v" \
"../../../../lsu.srcs/sources_1/new/top.v" \

vlog -64 -incr -mfcu -sv -work xil_defaultlib  \
"../../../../lsu.srcs/sim_1/new/tb.sv" \

