######################################################################
#
# File name : tb_elaborate.do
# Created on: Thu Nov 09 13:46:37 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -debugdb -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.tb -o tb_opt
