######################################################################
#
# File name : tb_elaborate.do
# Created on: Wed Nov 08 15:34:47 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -suppress 10016 -debugdb -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -work xil_defaultlib xil_defaultlib.tb -o tb_opt
