######################################################################
#
# File name : tb_wave.do
# Created on: Wed Nov 08 11:39:42 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
