######################################################################
#
# File name : tb_wave.do
# Created on: Thu Nov 09 11:36:00 JST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
